### ISSUE TITLE
Recipe App Kanban Board

### ISSUE THREAD

**Issue by Retky** [Retky/RecipeApp#22]
## Hello 👋🏻 
For this project we are a team of 2 (@Alexr16 🦁 & @Retky🦊)
### [Kanban Board](https://github.com/users/Retky/projects/2/views/1)

**Comment by gemmen29** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- Descriptive information ✔️
- Tasks are distributed equally ✔️

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Required Changes ♻️
- [x] Kindly provide a description for all tasks as per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Has%20a%20description%20of%20the%20task.). The tests tasks do not have any description.
![image](https://user-images.githubusercontent.com/24703171/180823266-907c85c1-d4e0-4521-bb31-e620072b5ac7.png)
![image](https://user-images.githubusercontent.com/24703171/180823507-ab766d56-bba0-4263-89e2-3e984c5af832.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShadyShawkat** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
